language: node_js
node_js:
  - "8"
before_install:
  - npm i -g codecov
install:
  - npm i
script:
  - npm run test
  - npm run cover
  - npm run build
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
