language: node_js
node_js:
  - '8'
before_install:
  - npm i -g codecov
install:
  - npm i
script:
  - npm run lint
  - npm run cover
  - npm run build
branches:
  only:
    - master
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  skip-cleanup: true
  email: iamdevlinph@gmail.com
  api_key:
    secure: UHCPYmmPPW2lzznKXn+pLmy3Ncfa8EPwm9X9DuoT56a3CSNIyXrbmHRp2gTmUxE24TNneLA5zHn/kZ9lo1VXIky8WN2qGDO4yojHEGoedeei8pS2hXcQlqqVXOMHypp+10Syfd15+Bo0zkUwR26shZ0y3omEXdgncn7Vcz8a+15EOC1uOnk0J4FHmQlhxKpH/lwo1yI+Nm0dAEJKAkujKQFKMdpI3Wcm9l5POUEJXRo0Um6V4qWrbF2Ukt760tkawPCy8GJ+PoQcSUaE7bUhHZWRUa0O7IM/87iWOZMjVXsh9EPDUZ/67HYgIej1pATvJC64bUnfKMdowUdE6ezZiFYRMYSQDy1lTk65kxY0YxW8McHl3Cfi7qDlQseJkKyXX56k+rPcgVH5dfWTx0M0TexodktG50RNwqpFeQSFmm7BgQy17NEjXuURpIT9xnmc4dyc+4YNZ8HdIFumoouqm/uE2WhSVEnQLSxu0VHRivC7zlNN2bebdfDAOjPGeLLtkPQr1MFSNbiwsoytvOKAhemXnLp7QAQx5i10dRBpgKSR/9AAZeQ+1HPQma3LlKCTV5deaqRVOT5paxH6cv+StkMyywoHrx7nzLqJTbss/0AQqTk/oj03IGjVWziBOZ3+fe0boMguTLApErGZhg4R0W0ZDsDGkgfosbunuC9fzmc=
  on:
    branch: master
