language: node_js
node_js:
  - "8"
install:
  - npm install -g codecov
script:
  - npm run test
  - npm run cover
  - npm run build
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
