codecov:
  strict_yaml_branch: master  # only use the latest copy on master branch

coverage:
  precision: 2
  round: down
  status:
    patch: false
    project:
      default:
        # basic
        target: 90%
